packages:
  - apps/*
  - packages/*

catalog:
  '@aws-sdk/client-s3': 3.873.0
  '@aws-sdk/s3-request-presigner': 3.873.0
  '@dotenvx/dotenvx': 1.49.1
  '@eslint/js': ^9.32.0
  '@hono/node-server': 1.19.0
  '@mdx-js/rollup': ^3.1.0
  '@node-rs/jieba': ^2.0.1
  '@prisma/adapter-pg': ^6.15.0
  '@prisma/client': ^6.15.0
  '@react-router/dev': ^7.8.2
  '@react-router/fs-routes': ^7.8.2
  '@react-router/node': ^7.8.2
  '@remotion/animation-utils': 4.0.339
  '@remotion/bundler': 4.0.339
  '@remotion/cli': 4.0.339
  '@remotion/fonts': 4.0.339
  '@remotion/google-fonts': 4.0.339
  '@remotion/lambda': 4.0.339
  '@remotion/layout-utils': 4.0.339
  '@remotion/player': 4.0.339
  '@remotion/preload': 4.0.339
  '@remotion/renderer': 4.0.339
  '@remotion/serverless-client': 4.0.339
  '@remotion/transitions': 4.0.339
  '@storybook/addon-docs': ^9.1.2
  '@storybook/react-vite': ^9.1.2
  '@tailwindcss/vite': 4.1.12
  '@turbo/gen': ^2.5.6
  '@types/archiver': ^6.0.3
  '@types/flake-idgen': ^0.1.34
  '@types/handlebars-helpers': ^0.5.6
  '@types/langdetect': ^0.2.2
  '@types/lodash-es': 4.17.12
  '@types/node': 24.1.0
  '@types/nodemailer': ^7.0.1
  '@types/pg': ^8.15.5
  '@types/react': 19.1.9
  '@types/react-dom': 19.1.7
  '@types/web-push': ^3.6.4
  '@types/xml2js': ^0.4.14
  '@vidstack/react': ^1.12.13
  '@vitejs/plugin-react': ^5.0.1
  apify-client: ^2.15.1
  archiver: ^7.0.1
  browser-image-compression: ^2.0.2
  bullmq: 5.58.6
  chalk: 5.6.0
  change-case-all: 2.1.0
  class-variance-authority: ^0.7.1
  clsx: 2.1.1
  commander: 14.0.0
  compromise: ^14.14.4
  css-select: ^6.0.0
  csstype: ^3.1.3
  dayjs: 1.11.13
  dedent: 1.6.0
  dotenv: 17.2.1
  eslint: ^9.32.0
  eslint-config-prettier: ^10.1.8
  fast-json-patch: 3.1.1
  fastq: ^1.19.1
  flake-idgen: ^1.4.0
  globals: ^16.3.0
  google-auth-library: ^10.3.0
  handlebars: ^4.7.8
  hono: 4.8.5
  htmlparser2: ^10.0.0
  husky: ^9.1.7
  image-size: ^2.0.2
  isbot: ^5.1.30
  iso-639-1: 3.1.5
  jose: ^6.0.13
  jotai: 2.13.1
  jotai-devtools: ^0.12.0
  jotai-history: ^0.4.3
  jotai-optics: ^0.4.0
  json-to-zod: ^1.1.2
  langdetect: ^0.2.1
  lodash-es: 4.17.21
  lucide-react: 0.536.0
  marked: ^16.2.1
  marked-custom-heading-id: ^2.0.15
  mime: 4.0.7
  mongoose: ^8.16.5
  node-html-parser: ^7.0.1
  nodemailer: ^7.0.5
  openai: 5.12.2
  p-map: ^7.0.3
  pg: ^8.16.3
  pino: 9.7.0
  pino-abstract-transport: ^2.0.0
  pino-pretty: ^13.0.0
  pino-roll: ^3.1.0
  postcss-nesting: ^13.0.2
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  prisma: ^6.15.0
  prisma-json-types-generator: ^3.6.0
  radix-ui: ^1.4.3
  react: 19.1.1
  react-dom: 19.1.1
  react-is: ^19.1.1
  react-resizable-panels: ^3.0.4
  react-router: ^7.8.2
  react-router-hono-server: ^2.21.0
  react-share: ^5.2.2
  react-virtuoso: ^4.14.0
  recharts: ^3.1.2
  redis: ^5.8.2
  remotion: 4.0.339
  rollup: 4.47.1
  rollup-plugin-dts: 6.2.3
  shadcn: ^2.10.0
  sonner: ^2.0.7
  storybook: ^9.1.2
  stripe: ^18.4.0
  tailwind-merge: 3.3.1
  tailwindcss: 4.1.12
  tsup: 8.5.0
  tsx: ^4.20.3
  turbo: ^2.5.5
  tw-animate-css: 1.3.6
  typescript: ^5.8.3
  typescript-eslint: ^8.38.0
  undici: ^7.16.0
  vite: 7.1.2
  vite-plugin-static-copy: ^3.1.2
  vite-plugin-svgr: 4.3.0
  vite-tsconfig-paths: 5.1.4
  vitest: 3.2.4
  web-push: ^3.6.7
  xml2js: ^0.6.2
  yaml: ^2.8.1
  zod: 4.0.15
  zod-validation-error: 4.0.1

catalogMode: prefer

patchedDependencies:
  fast-json-patch: patches/fast-json-patch.patch

useNodeVersion: 22.19.0
